"""
exit_model.py — LightGBM Stop Recovery Classifier
===================================================
Predicts whether price will recover >50% of loss within 10 trading days
after a stop is triggered. Used to decide: hold through stop or exit.

Training data: cache_backtester/stop_outcomes.csv (generated by backtester_v2.py)
Model saved to: cache_backtester/exit_model.pkl

Usage:
    python v2/exit_model.py --train
    python v2/exit_model.py --predict --regime_now TRENDING_BULL --unrealized -0.08 --days 5
"""
from __future__ import annotations

import os
import sys
import json
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, os.path.expanduser("~/ai_trading_bot_v2"))
sys.path.insert(0, os.path.expanduser("~/ai_trading_bot_v2/v2"))

import numpy as np
import pandas as pd
import joblib

STOP_DATA_PATH  = os.path.expanduser("~/ai_trading_bot_v2/cache_backtester/stop_outcomes.csv")
MODEL_PATH      = os.path.expanduser("~/ai_trading_bot_v2/cache_backtester/exit_model.pkl")
FEATURES_PATH   = os.path.expanduser("~/ai_trading_bot_v2/cache_backtester/exit_model_features.json")

REGIME_VALUES = ["TRENDING_BULL", "CHOPPY", "BEAR"]

_cached_model = None
_cached_features = None


# ═══════════════════════════════════════════════════════════════════════════════
#  1. LOAD DATA
# ═══════════════════════════════════════════════════════════════════════════════

def load_stop_data() -> pd.DataFrame:
    """
    Load stop outcomes CSV and prepare for training.
    One-hot encodes regime columns, fills NaN with 0.
    """
    if not os.path.exists(STOP_DATA_PATH):
        print(f"ERROR: {STOP_DATA_PATH} not found.")
        print("Run the backtester first to generate stop outcome data.")
        return pd.DataFrame()

    df = pd.read_csv(STOP_DATA_PATH)
    if len(df) == 0:
        return pd.DataFrame()

    # One-hot encode regime columns
    for col in ["regime_entry", "regime_now"]:
        if col in df.columns:
            for regime in REGIME_VALUES:
                df[f"{col}_{regime}"] = (df[col] == regime).astype(float)
            df = df.drop(columns=[col])

    # Fill NaN
    df = df.fillna(0)

    return df


# ═══════════════════════════════════════════════════════════════════════════════
#  2. TRAIN MODEL
# ═══════════════════════════════════════════════════════════════════════════════

def train_exit_model(df: pd.DataFrame) -> Tuple:
    """
    Train LightGBM binary classifier to predict stop recovery.

    Returns:
        (model, feature_cols, metrics_dict)
    """
    import lightgbm as lgb
    from sklearn.model_selection import StratifiedKFold, cross_val_score

    # Define features and target
    drop_cols = ["date", "symbol", "recovered_10d"]
    feature_cols = [c for c in df.columns if c not in drop_cols]
    target = "recovered_10d"

    if target not in df.columns:
        print(f"ERROR: '{target}' column not found in data.")
        return None, [], {}

    X = df[feature_cols].values.astype(np.float32)
    y = df[target].values.astype(int)

    n_samples = len(y)
    n_positive = int(y.sum())
    n_negative = n_samples - n_positive

    print(f"\n  Training data: {n_samples} stops")
    print(f"  Recovered (1): {n_positive} ({n_positive / n_samples:.0%})")
    print(f"  Continued (0): {n_negative} ({n_negative / n_samples:.0%})")
    print(f"  Features: {len(feature_cols)}")

    # Model
    model = lgb.LGBMClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        class_weight="balanced",
        verbose=-1,
    )

    # 5-fold stratified cross-validation
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    auc_scores = cross_val_score(model, X, y, cv=cv, scoring="roc_auc")
    mean_auc = float(auc_scores.mean())
    std_auc = float(auc_scores.std())

    print(f"\n  Cross-validation AUC: {mean_auc:.4f} ± {std_auc:.4f}")
    print(f"  Per-fold: {[f'{s:.4f}' for s in auc_scores]}")

    # Train final model on all data
    model.fit(X, y)

    # Feature importances
    importances = model.feature_importances_
    imp_df = pd.DataFrame({
        "feature": feature_cols,
        "importance": importances,
    }).sort_values("importance", ascending=False)

    print(f"\n  Top 10 features:")
    for _, row in imp_df.head(10).iterrows():
        print(f"    {row['feature']:30s}  {row['importance']:6.0f}")

    # Save model
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    joblib.dump(model, MODEL_PATH)
    print(f"\n  Model saved: {MODEL_PATH}")

    # Save feature columns
    with open(FEATURES_PATH, "w") as f:
        json.dump(feature_cols, f)
    print(f"  Features saved: {FEATURES_PATH}")

    metrics = {
        "auc": mean_auc,
        "auc_std": std_auc,
        "n_samples": n_samples,
        "n_positive": n_positive,
        "n_features": len(feature_cols),
    }

    return model, feature_cols, metrics


# ═══════════════════════════════════════════════════════════════════════════════
#  3. PREDICT
# ═══════════════════════════════════════════════════════════════════════════════

def _load_model():
    """Load cached model and feature list."""
    global _cached_model, _cached_features

    if _cached_model is not None:
        return _cached_model, _cached_features

    if not os.path.exists(MODEL_PATH) or not os.path.exists(FEATURES_PATH):
        return None, None

    try:
        _cached_model = joblib.load(MODEL_PATH)
        with open(FEATURES_PATH) as f:
            _cached_features = json.load(f)
        return _cached_model, _cached_features
    except Exception:
        return None, None


def predict_exit(
    stop_context: Dict,
    model=None,
    feature_cols: Optional[List[str]] = None,
) -> float:
    """
    Predict probability of recovery after a stop trigger.

    Args:
        stop_context: dict with keys: regime_entry, regime_now, unrealized_pct,
                      days_held, ml_rank_entry, ml_rank_now, stop_pct, vix_now
        model: pre-loaded model (optional)
        feature_cols: feature column names (optional)

    Returns:
        Probability of recovery (0.0 to 1.0).
        Returns 0.0 if model not available (always exit).
    """
    if model is None or feature_cols is None:
        model, feature_cols = _load_model()

    if model is None or feature_cols is None:
        return 0.0

    # Build feature row matching training format
    row = {}

    # Numeric features
    for key in ["unrealized_pct", "days_held", "ml_rank_entry", "ml_rank_now",
                "stop_pct", "vix_now"]:
        row[key] = float(stop_context.get(key, 0))

    # One-hot encode regime fields
    regime_entry = stop_context.get("regime_entry", "")
    regime_now = stop_context.get("regime_now", "")
    for regime in REGIME_VALUES:
        row[f"regime_entry_{regime}"] = 1.0 if regime_entry == regime else 0.0
        row[f"regime_now_{regime}"] = 1.0 if regime_now == regime else 0.0

    # Build feature vector in correct column order
    X = np.array([[row.get(c, 0.0) for c in feature_cols]], dtype=np.float32)

    try:
        proba = model.predict_proba(X)[0, 1]
        return float(proba)
    except Exception:
        return 0.0


# ═══════════════════════════════════════════════════════════════════════════════
#  4. DECISION FUNCTION
# ═══════════════════════════════════════════════════════════════════════════════

def should_hold_through_stop(stop_context: Dict, threshold: float = 0.60) -> bool:
    """
    Should we hold through this stop trigger?

    Args:
        stop_context: dict with regime, loss, ML rank info
        threshold: minimum recovery probability to hold (default 0.60)

    Returns:
        True if model predicts >threshold probability of recovery.
    """
    proba = predict_exit(stop_context)
    return proba > threshold


# ═══════════════════════════════════════════════════════════════════════════════
#  5. MAIN
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Exit Model — Stop Recovery Classifier")
    parser.add_argument("--train", action="store_true", help="Train model from stop_outcomes.csv")
    parser.add_argument("--predict", action="store_true", help="Interactive prediction test")
    parser.add_argument("--regime_entry", default="TRENDING_BULL")
    parser.add_argument("--regime_now", default="TRENDING_BULL")
    parser.add_argument("--unrealized", type=float, default=-0.08)
    parser.add_argument("--days", type=int, default=5)
    parser.add_argument("--ml_entry", type=float, default=0.90)
    parser.add_argument("--ml_now", type=float, default=0.85)
    parser.add_argument("--stop_pct", type=float, default=0.08)
    parser.add_argument("--vix", type=float, default=20.0)
    args = parser.parse_args()

    if args.train:
        print("=" * 60)
        print("  EXIT MODEL TRAINING")
        print("=" * 60)

        df = load_stop_data()
        if len(df) == 0:
            print("No training data. Run backtester with stop instrumentation first.")
            sys.exit(1)

        model, features, metrics = train_exit_model(df)

        print(f"\n{'=' * 60}")
        print(f"  RESULT: AUC = {metrics['auc']:.4f}")
        if metrics["auc"] >= 0.65:
            print("  STATUS: Usable — AUC > 0.65 threshold")
        elif metrics["auc"] >= 0.55:
            print("  STATUS: Marginal — AUC 0.55-0.65, use with caution")
        else:
            print("  STATUS: Not usable — AUC < 0.55, no better than random")
        print(f"{'=' * 60}")

    elif args.predict:
        context = {
            "regime_entry": args.regime_entry,
            "regime_now": args.regime_now,
            "unrealized_pct": args.unrealized,
            "days_held": args.days,
            "ml_rank_entry": args.ml_entry,
            "ml_rank_now": args.ml_now,
            "stop_pct": args.stop_pct,
            "vix_now": args.vix,
        }

        proba = predict_exit(context)
        hold = should_hold_through_stop(context)

        print(f"\nStop context:")
        for k, v in context.items():
            print(f"  {k:20s}: {v}")
        print(f"\n  Recovery probability: {proba:.1%}")
        print(f"  Decision: {'HOLD through stop' if hold else 'EXIT at stop'}")

    else:
        # Show model status
        model, features = _load_model()
        if model is not None:
            print(f"Exit model loaded: {len(features)} features")
            print(f"  Model: {MODEL_PATH}")
            print(f"  Features: {FEATURES_PATH}")
        else:
            print("No exit model trained yet. Run: python v2/exit_model.py --train")
