"""
ablation.py — Measure each stacked overlay's contribution to OOS CAGR.

The backtester has ~12 overlays stacked on top of the base ML ranker:
  TCPS day-7 scaling, breakeven move, hold extension, Friday delay,
  ML-still-believes stop hold, conviction calls, VIX vol scalar,
  cascade freeze, vol-proportional cooldown, biotech gate, quality gate,
  earnings exclusion, SPY 5d momentum filter.

This script runs the backtest with each overlay disabled (one at a time)
and reports the CAGR delta. Anything whose delta is smaller than 2× the
noise floor (from noise_floor.py) is statistically dead weight and should
be deleted.

How it works:
  Each overlay is gated on an environment variable read by the patched
  backtester. ABLATE=NAME disables overlay NAME. The patched backtester
  is at v2/backtester_v2_ablation.py — generated by this script the first
  time it runs.

Usage:
  cd ~/ai_trading_bot_v2
  python3.11 tools/ablation.py --days 3650

  # or run a specific overlay only:
  python3.11 tools/ablation.py --only tcps,conviction_calls
"""

from __future__ import annotations
import argparse
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_BT = REPO / "v2" / "backtester_v2.py"
ABLATION_BT = REPO / "v2" / "backtester_v2_ablation.py"

# Each overlay: (name, marker_regex_in_source, replacement_template)
# Replacement wraps the relevant block in `if not _is_disabled("NAME"):`
#
# Markers chosen to be unique anchor strings already present in the source.
OVERLAYS = [
    ("tcps",
     "# TCPS: Trajectory-Conditioned Position Scaling",
     "if hold_d == 7:",
     'if hold_d == 7 and not _ablate("tcps"):'),
    ("breakeven",
     "# Fix 4: move stop to breakeven once up 8%",
     "if unrealized_pct >= 0.08:",
     'if unrealized_pct >= 0.08 and not _ablate("breakeven"):'),
    ("ml_stop_hold",
     "# ML conviction check — only hold through stop in TRENDING_BULL",
     "if not _ml_still_believes:",
     'if not _ml_still_believes or _ablate("ml_stop_hold"):'),
    ("hold_extension",
     "# Profit-based hold extension: let winners run.",
     "extended   = int(base_max * 1.5) if (unrealized_pct > 0.08 and ml_score > 0.85) else base_max",
     'extended   = int(base_max * 1.5) if (unrealized_pct > 0.08 and ml_score > 0.85 and not _ablate("hold_extension")) else base_max'),
    ("friday_delay",
     "# Friday exit delay — OOS validated p=0.035",
     "if pd.Timestamp(date).weekday() == 4:",
     'if pd.Timestamp(date).weekday() == 4 and not _ablate("friday_delay"):'),
    ("conviction_calls",
     "from conviction_calls import conviction_score, compute_options_budget, bs_call",
     "if _conv >= 0.3:",
     'if _conv >= 0.3 and not _ablate("conviction_calls"):'),
    ("vix_vol_scalar",
     "# ── Daily VIX scalar — shared by momentum AND meanrev",
     "if _vix_level >= 35.0:",
     'if _vix_level >= 35.0 and not _ablate("vix_vol_scalar"):'),
    ("cascade_freeze",
     "# Stop cascade sensor",
     "cascade_freeze = len(recent_stop_dates) >= 2",
     'cascade_freeze = len(recent_stop_dates) >= 2 and not _ablate("cascade_freeze")'),
    ("vol_cooldown",
     "# Vol-proportional cooldown",
     "_cool_days = 180 if _cool_vol > 0.70 else 90 if _cool_vol > 0.50 else 45 if _cool_vol > 0.30 else 15",
     '_cool_days = (180 if _cool_vol > 0.70 else 90 if _cool_vol > 0.50 else 45 if _cool_vol > 0.30 else 15) if not _ablate("vol_cooldown") else 0'),
    ("quality_gate",
     "# Quality gate — don't buy high-momentum low-quality stocks",
     "if quality < q_min:",
     'if quality < q_min and not _ablate("quality_gate"):'),
    ("spy_5d_filter",
     "# SPY 5-day momentum filter — don't buy into weakness",
     "if _spy_5d_returns.get(date, 0.0) < -0.015:",
     'if _spy_5d_returns.get(date, 0.0) < -0.015 and not _ablate("spy_5d_filter"):'),
    ("biotech_gate",
     "# Biotech gate — XLV high-vol names",
     'if sector_map.get(s) == "XLV":',
     'if sector_map.get(s) == "XLV" and not _ablate("biotech_gate"):'),
    ("earnings_exclusion",
     "# Earnings calendar filter",
     "if _earn and min(abs((date - d).days) for d in _earn) <= 5:",
     'if _earn and not _ablate("earnings_exclusion") and min(abs((date - d).days) for d in _earn) <= 5:'),
]

ABLATE_HELPER = '''
# ── ABLATION HARNESS ──────────────────────────────────────────────────
import os as _ablate_os
_ABLATED = set(_ablate_os.environ.get("ABLATE", "").split(","))
def _ablate(name: str) -> bool:
    return name in _ABLATED
'''

RESULT_PATTERNS = {
    "cagr":   re.compile(r"CAGR[^0-9\-]*([\-\d\.]+)\s*%"),
    "sharpe": re.compile(r"Sharpe[^0-9\-]*([\-\d\.]+)"),
    "maxdd":  re.compile(r"Max\s*DD[^0-9\-]*([\-\d\.]+)\s*%"),
}


def build_ablation_backtester() -> None:
    """Patch backtester_v2.py into backtester_v2_ablation.py with ablation hooks."""
    src = SRC_BT.read_text()

    # Inject helper near the top (after imports, before first def).
    src = src.replace(
        "CACHE_DIR = \"cache_prices\"",
        "CACHE_DIR = \"cache_prices\"\n" + ABLATE_HELPER,
    )

    applied = []
    failed = []
    for name, comment_anchor, line_anchor, replacement in OVERLAYS:
        if comment_anchor not in src:
            failed.append((name, "comment anchor missing"))
            continue
        # Find the line_anchor AFTER the comment anchor to avoid false matches.
        idx = src.find(comment_anchor)
        rest = src[idx:]
        if line_anchor not in rest:
            failed.append((name, "line anchor missing"))
            continue
        # Replace only the FIRST occurrence after the comment.
        new_rest = rest.replace(line_anchor, replacement, 1)
        src = src[:idx] + new_rest
        applied.append(name)

    ABLATION_BT.write_text(src)
    print(f"[build] generated {ABLATION_BT}")
    print(f"[build] applied {len(applied)}/{len(OVERLAYS)} overlays: {', '.join(applied)}")
    if failed:
        print(f"[build] FAILED: {failed}")
        print("[build] re-run will overwrite. Check anchors.")


def run_backtest(env_extra: dict, log_path: Path, days: int) -> int:
    env = os.environ.copy()
    env.update(env_extra)
    with log_path.open("w") as logf:
        rc = subprocess.run(
            [sys.executable, str(ABLATION_BT), "--days", str(days), "--oos"],
            env=env, stdout=logf, stderr=subprocess.STDOUT,
        ).returncode
    return rc


def parse_results(log_path: Path) -> dict[str, float] | None:
    text = log_path.read_text()
    out = {}
    for k, pat in RESULT_PATTERNS.items():
        matches = pat.findall(text)
        if not matches:
            return None
        try:
            out[k] = float(matches[-1])
        except ValueError:
            return None
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=3650)
    ap.add_argument("--only", type=str, default="",
                    help="Comma-separated list of overlays to test (default: all)")
    ap.add_argument("--rebuild", action="store_true",
                    help="Force rebuild of backtester_v2_ablation.py")
    args = ap.parse_args()

    os.chdir(REPO)
    log_dir = REPO / "tools" / "ablation_logs"
    log_dir.mkdir(parents=True, exist_ok=True)

    if args.rebuild or not ABLATION_BT.exists():
        build_ablation_backtester()

    overlays_to_test = [o[0] for o in OVERLAYS]
    if args.only:
        only = set(args.only.split(","))
        overlays_to_test = [o for o in overlays_to_test if o in only]

    print(f"=== ABLATION TEST ({len(overlays_to_test)} overlays + 1 baseline) ===")
    print()
    t0 = time.time()
    results = {}

    # Baseline first.
    print("--- baseline (all overlays on) ---")
    rc = run_backtest({}, log_dir / "baseline.log", args.days)
    if rc != 0:
        print(f"  [FAIL] rc={rc}")
        return
    baseline = parse_results(log_dir / "baseline.log")
    if baseline is None:
        print("  [FAIL] could not parse baseline")
        return
    print(f"  CAGR={baseline['cagr']:+.2f}%  Sharpe={baseline['sharpe']:.2f}  "
          f"MaxDD={baseline['maxdd']:.2f}%")
    results["baseline"] = baseline

    for i, name in enumerate(overlays_to_test, start=1):
        print(f"\n--- {i}/{len(overlays_to_test)}  ABLATE={name} ---")
        log_path = log_dir / f"ablate_{name}.log"
        rc = run_backtest({"ABLATE": name}, log_path, args.days)
        if rc != 0:
            print(f"  [FAIL] rc={rc}")
            continue
        parsed = parse_results(log_path)
        if parsed is None:
            print(f"  [FAIL] could not parse {log_path}")
            continue
        d_cagr = parsed["cagr"] - baseline["cagr"]
        d_sharpe = parsed["sharpe"] - baseline["sharpe"]
        d_dd = parsed["maxdd"] - baseline["maxdd"]
        print(f"  CAGR={parsed['cagr']:+.2f}% (Δ{d_cagr:+.2f})  "
              f"Sharpe={parsed['sharpe']:.2f} (Δ{d_sharpe:+.2f})  "
              f"MaxDD={parsed['maxdd']:.2f}% (Δ{d_dd:+.2f})")
        results[name] = parsed

    # Report
    elapsed = (time.time() - t0) / 60
    print("\n" + "=" * 78)
    print(f"ABLATION RESULTS  ({elapsed:.1f} min total)")
    print("=" * 78)
    print(f"{'overlay':<22}  {'CAGR':>8}  {'ΔCAGR':>8}  {'Sharpe':>8}  {'ΔShp':>7}  {'MaxDD':>8}")
    bcagr, bsh, bdd = baseline["cagr"], baseline["sharpe"], baseline["maxdd"]
    print(f"{'(baseline)':<22}  {bcagr:>+7.2f}%  {'—':>8}  {bsh:>8.2f}  {'—':>7}  {bdd:>+7.2f}%")
    print("-" * 78)
    rows = []
    for name in overlays_to_test:
        if name not in results:
            continue
        r = results[name]
        rows.append((name, r["cagr"]-bcagr, r["sharpe"]-bsh, r))
    # Sort by abs(ΔCAGR) descending — biggest contributors first.
    rows.sort(key=lambda x: abs(x[1]), reverse=True)
    for name, dcagr, dshp, r in rows:
        # Interpretation: ΔCAGR is what disabling does. NEGATIVE = overlay HELPS.
        # POSITIVE = overlay HURTS (disabling improved result).
        flag = " HELPS" if dcagr < -0.5 else (" HURTS" if dcagr > 0.5 else " ~ noise")
        print(f"{name:<22}  {r['cagr']:>+7.2f}%  {dcagr:>+7.2f}  "
              f"{r['sharpe']:>8.2f}  {dshp:>+7.2f}  {r['maxdd']:>+7.2f}% {flag}")
    print()
    print("Read this against your noise floor (run noise_floor.py first):")
    print("  ΔCAGR within ±2σ of noise = statistically dead weight.")
    print("  Anything that HURTS (disabling improves) = delete immediately.")
    print("  Only keep overlays that HELP by more than 2σ.")


if __name__ == "__main__":
    main()
